name       : ruby-i18n
version    : 0.8.0
release    : 1
source     :
    - https://rubygems.org/downloads/i18n-0.8.0.gem : eefbf6cbe4432e41e6ad69bd2a1f6df1130f65bf6ad036c8344b25840fa5da02
license    : MIT
component  : programming.ruby
summary    : RubyGem - i18n
description: |
    New wave Internationalization support for Ruby.
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - concurrent-ruby
install    : |
    %gem_install
